=== pharbuz-spica/spicamonitoring-airflowplugin/venv/lib/python3.6/site-packages/plugin_sdk/json_schema/schema_local.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "$id": "schema_local.json",
    "required": ["name", "version", "type", "entity", "metrics", "metricGroup"],
    "title": "plugin.json top level",
    "properties": {
        "name": {
            "type": "string",
            "minLength": 1,
            "description": "A unique plugin name in Java package format.",
            "pattern": "^custom.(jmx|pmi|python)(\\.[a-zA-Z][a-zA-Z0-9_-]*)+$"
        },
        "version": {
            "type": "string",
            "description": "The plugin version, must be updated whenever the plugin definition is updated.",
            "pattern": "^\\d+.\\d+(.\\d+)?$"
        },
        "type": {
            "type": "string",
            "description": "The plugin type. Currently only python is avilable",
            "enum": ["JMX", "python"]
        },
        "entity": {
            "type": "string",
            "description": "Entity type upon which the plugin is activated",
            "enum": [ "HOST", "PROCESS_GROUP_INSTANCE"]
        },
        "metricGroup": {
            "type": "string",
            "minLength": 1,
            "description": "Metric group is used for grouping custom metrics into a hierarchical namespace where different sources, for example multiple plugins can contribute. Moreover, metric group becomes primary part of metric key. Hence once defined it could not be changed.",
            "pattern": "^(\/?[-a-zA-Z0-9_.]+)+$"
        },
        "processTypes": {
            "type": "array",
            "description": "Type of process that plugin monitors, as defined in the processTypes table below. This serves as an alternative to processTypeNames. This is deprecated method, please use technologies instead.",
            "items": {
                "type": "integer",
                "minimum": 0
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "processTypeNames": {
            "description": "Type of process that plugin monitors, as defined in the processTypes table below. This is deprecated method, please use technologies instead.",
            "$ref": "known_process_types.json",
            "minItems": 1,
            "uniqueItems": true
        },
        "technologies": {
            "description": "Type of technology that plugin monitors, as can be viewed on Technologies overview page.",
            "$ref": "known_technologies.json",
            "minItems": 0,
            "uniqueItems": true
        },
        "metrics": {
            "description": "The section defining metrics; see Metrics section for reference",
            "$ref": "metrics.json"
        },
        "properties": {
            "type": "array",
            "description": "Configuration properties the plugin can accept.",
            "$ref": "properties.json"
        },
        "ui": {
            "description": "This part of the JSON defines how metrics are charted on each Process page.",
            "$ref": "ui.json"
        },
        "configUI": {
            "description": "The configUI section defines the configuration fields that are displayed in the UI.",
            "$ref": "configui.json"
        },
        "source": {
            "description": "Python metadata used by ActiveGate PluginModule python engine",
            "$ref": "source.json"}
    },
  "dependencies": {
    "processTypes": {"not": {"required": ["processTypeNames", "technologies"]}},
    "processTypeNames": {"not": {"required": ["processTypes", "technologies"]}}

  }

}

=== pharbuz-spica/spicamonitoring-airflowplugin/plugin.json
{
  "name": "custom.python.apache_spark_dt_plugin",
  "version": "0.80",
  "type": "python",
  "entity": "PROCESS_GROUP_INSTANCE",
  "technologies": [
    "APACHE_SPARK"
  ],
  "source": {
    "package": "apache_spark_dt_plugin",
    "className": "ApacheSparkDTPlugin",
    "install_requires": [
      "requests>=2.6.0"
    ],
    "activation": "Singleton"
  },
  "metricGroup": "Apache_Spark_Custom",
  "metrics": [
    {
      "timeseries": {
        "key": "numTasks",
        "unit": "Count",
        "displayname": "numTasks",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numActiveTasks",
        "unit": "Count",
        "displayname": "numActiveTasks",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numCompletedTasks",
        "unit": "Count",
        "displayname": "numCompletedTasks",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numSkippedTasks",
        "unit": "Count",
        "displayname": "numSkippedTasks",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numFailedTasks",
        "unit": "Count",
        "displayname": "numFailedTasks",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numActiveStages",
        "unit": "Count",
        "displayname": "numActiveStages",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numCompletedStages",
        "unit": "Count",
        "displayname": "numCompletedStages",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numSkippedStages",
        "unit": "Count",
        "displayname": "numSkippedStages",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "numFailedStages",
        "unit": "Count",
        "displayname": "numFailedStages",
        "dimensions": [
          "job_name",
          "app_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "rddBlocks",
        "unit": "Count",
        "displayname": "Executor | rddBlocks",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "memoryUsed",
        "unit": "Byte",
        "displayname": "Executor | memoryUsed",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "diskUsed",
        "unit": "Byte",
        "displayname": "Executor | diskUsed",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalCores",
        "unit": "Count",
        "displayname": "Executor | totalCores",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "maxTasks",
        "unit": "Count",
        "displayname": "Executor | maxTasks",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "activeTasks",
        "unit": "Count",
        "displayname": "Executor | activeTasks",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "failedTasks",
        "unit": "Count",
        "displayname": "Executor | failedTasks",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "completedTasks",
        "unit": "Count",
        "displayname": "Executor | completedTasks",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalTasks",
        "unit": "Count",
        "displayname": "Executor | totalTasks",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalDuration",
        "unit": "MilliSecond",
        "displayname": "Executor | totalDuration",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalGCTime",
        "unit": "MilliSecond",
        "displayname": "Executor | totalGCTime",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalInputBytes",
        "unit": "Byte",
        "displayname": "Executor | totalInputBytes",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalShuffleRead",
        "unit": "Count",
        "displayname": "Executor | totalShuffleRead",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalShuffleWrite",
        "unit": "Count",
        "displayname": "Executor | totalShuffleWrite",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "maxMemory",
        "unit": "Byte",
        "displayname": "Executor | maxMemory",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "usedOnHeapStorageMemory",
        "unit": "Byte",
        "displayname": "Executor | usedOnHeapStorageMemory",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "usedOffHeapStorageMemory",
        "unit": "Byte",
        "displayname": "Executor | usedOffHeapStorageMemory",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalOnHeapStorageMemory",
        "unit": "Byte",
        "displayname": "Executor | totalOnHeapStorageMemory",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "totalOffHeapStorageMemory",
        "unit": "Byte",
        "displayname": "Executor | totalOffHeapStorageMemory",
        "dimensions": [
          "app_name",
          "host_name"
        ]
      }
    },
    {
      "timeseries": {
        "key": "progress",
        "unit": "Count",
        "displayname": "Application progress",
        "dimensions": [
          "app_name"
        ]
      }
    }
  ],
  "configUI": {
    "displayName": "SpicaSolutions Apache Spark Plugin",
    "properties": [
      {
        "key": "port",
        "displayName": "Apache Spark WebUI port"
      },
      {
        "key": "base_url",
        "displayName": "Apache Spark Base URL",
        "displayHint": "If you have any prefix or suffix for your API Endpoints, you can add it here"
      }
    ]
  },
  "properties": [
    {
      "key": "port",
      "type": "String",
      "defaultValue": "8088"
    },
    {
      "key": "base_url",
      "type": "String",
      "defaultValue": "http://opr-jpk-009.lnx.mf.gov.pl:8088"
    }
  ]
}
